<section class="section community text-center" id="community">
<div class="tekstblok">
<h1>BIERVERTELLERS</h1>
<p><img style="margin-bottom: -20.0px;" src="http://www.debierverteller.nl/wp-content/uploads/2015/12/bolhoed_zwart.png" alt="De Bierverteller Tomas Schroën Hubert Hecker" width="60" height="60"><br>
<span class="collapseomatic  colomat-visited" id="id5dd511683b690" tabindex="" title="CHAIM">CHAIM</span></p><div id="target-id5dd511683b690" class="collapseomatic_content " style="display: none;">
<div style="max-width: 472px; margin-left: auto; margin-right: auto;"><img class="aligncenter size-full wp-image-988" src="http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-chaim-2.jpg" alt="Bierverteller Chaim" width="472" height="687" srcset="http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-chaim-2.jpg 472w, http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-chaim-2-206x300.jpg 206w" sizes="(max-width: 472px) 100vw, 472px"><br>
<strong><span style="color: #e63939;">a.k.a.:</span></strong> “De Geek”<br>
<strong><span style="color: #e63939;">Geboortedatum:</span></strong> 01-09-1984<br>
<strong><span style="color: #e63939;">Geboren te:</span></strong> Utrecht<br>
<strong><span style="color: #e63939;">Bierverteller sinds:</span></strong> Augustus 2016<br>
<strong><span style="color: #e63939;">Favoriete bierstijl:</span></strong> Als het maar goed gemaakt is!<br>
<strong><span style="color: #e63939;">Specialiteit:</span></strong> Nieuwe ontdekkingen<br>
<strong><span style="color: #e63939;">“Vanaf 2002&nbsp;werk ik in de horeca.</span></strong> Eerst naast mijn studie Nederlands en later full time. Hierdoor bracht ik vele uren aan en achter de bar door van verschillende Utrechtse horecagelegenheden. Bij Café Olivier ben ik mij echt gaan specialiseren in bier. Ik ben als een gek gaan lezen, proeven en brouwen, net zolang tot ik in staat was de door De Bierverteller georganiseerde bierquiz op het Utrechts Bierbrouwers Festival te winnen. Deze overwinning zorgde er samen met mijn hobbybrouwervaring en algehele beergeekiness voor, dat ik een paar maanden later als Bierverteller aan de slag kon gaan. Sinds maart 2018 mag ik mij gediplomeerd biersommelier noemen. Bij De Bierverteller richt ik me op de inkoop en geef ik veel proeverijen. Ik vind het leuk om in de winkel een goede balans te vinden tussen toegankelijke en extreme bieren zodat er voor ieder wat wils is. Tijdens de proeverijen ga ik graag in gesprek met de proevers, daardoor kom ik achter individuele interesses en kan ik iedere groep de informatie geven die voor hen het meest interessant is.”<br>
</div></div>
<p><img style="margin-bottom: -20.0px;" src="http://www.debierverteller.nl/wp-content/uploads/2015/12/bolhoed_zwart.png" alt="De Bierverteller Tomas Schroën Hubert Hecker" width="60" height="60"><br>
<span class="collapseomatic " id="id5dd511683b6fa" tabindex="" title="EELCO">EELCO</span></p><div id="target-id5dd511683b6fa" class="collapseomatic_content " style="display: none;">
<div style="max-width: 472px; margin-left: auto; margin-right: auto;"><img class="aligncenter size-full wp-image-912" src="http://www.debierverteller.nl/wp-content/uploads/2018/03/bierverteller-eelco.jpg" alt="Bierverteller Eelco Utrecht" width="472" height="687" srcset="http://www.debierverteller.nl/wp-content/uploads/2018/03/bierverteller-eelco.jpg 472w, http://www.debierverteller.nl/wp-content/uploads/2018/03/bierverteller-eelco-206x300.jpg 206w" sizes="(max-width: 472px) 100vw, 472px"><br>
<strong><span style="color: #e63939;">a.k.a.:</span></strong> De Ervaringsdeskundige<br>
<strong><span style="color: #e63939;">Geboortedatum:</span></strong> 26-04-1974<br>
<strong><span style="color: #e63939;">Geboren te:</span></strong> Groningen<br>
<strong><span style="color: #e63939;">Bierverteller sinds:</span></strong> April 2017<br>
<strong><span style="color: #e63939;">Favoriete bierstijl:</span></strong> Allemaal<br>
<strong><span style="color: #e63939;">Specialiteit:</span></strong> Voorlichting<br>
<strong><span style="color: #e63939;">“Toen ik voor het eerst een De Koninck proefde</span></strong> ging er een nieuwe wereld van smaak en aroma voor me open. Tijdens mijn studententijd bleef ik genieten van “speciale” bieren, terwijl het toch vooral pils was wat om mij heen de klok sloeg. Van 2006-2015 heb ik gewerkt bij Berts Bierhuis, en sindsdien is mijn liefde voor (en kennis van) de bierwereld exponentieel gegroeid. Daarna ben ik als mede-oprichter betrokken geweest bij de Brewpub van Oproer te Utrecht. Ik vind het te gek om mensen te helpen hun voorliefde voor bier te verkennen, en ze kennis te laten maken met nieuwe smaaksensaties. En de wens om zelf te ontdekken is er ook nog steeds!”<br>
</div></div>
<p><img style="margin-bottom: -20.0px;" src="http://www.debierverteller.nl/wp-content/uploads/2015/12/bolhoed_zwart.png" alt="De Bierverteller Tomas Schroën Hubert Hecker" width="60" height="60"><br>
<span class="collapseomatic " id="id5dd511683b72b" tabindex="" title="HUBERT">HUBERT</span></p><div id="target-id5dd511683b72b" class="collapseomatic_content " style="display: none;">
<div style="max-width: 472px; margin-left: auto; margin-right: auto;"><img class="aligncenter size-full wp-image-1016" src="http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-hubert-2.jpg" alt="Bierverteller Hubert Hecker" width="472" height="687" srcset="http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-hubert-2.jpg 472w, http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-hubert-2-206x300.jpg 206w" sizes="(max-width: 472px) 100vw, 472px"><br>
<strong><span style="color: #e63939;">a.k.a.:</span></strong> “Meesterproever”<br>
<strong><span style="color: #e63939;">Geboortedatum:</span></strong> 21-9-1986<br>
<strong><span style="color: #e63939;">Geboren te:</span></strong> Wessem<br>
<strong><span style="color: #e63939;">Bierverteller sinds:</span></strong> Januari 2015<br>
<strong><span style="color: #e63939;">Favoriete bierstijl:</span></strong> Droog, bitter en laag in alcohol<br>
<strong><span style="color: #e63939;">Specialiteit:</span></strong> Culicombi’s<br>
<strong><span style="color: #e63939;">“Twaalf jaar lang heb ik in de horeca gewerkt,</span></strong> waarvan de laatste zes jaren bij café In de Blaauwe Hand in Nijmegen. Hier is mijn liefde voor bier en de wereld er omheen ontstaan. Begin 2015 vroeg Tomas, met wie ik al sinds mijn tienerjaren bevriend ben, of ik het leuk zou vinden om mede-Bierverteller te worden om zo samen de lasten, maar vooral de lusten te kunnen delen. Hier hoefde ik niet lang over na te denken. Daar hoorde ook een gedegen en overlegbare kennis bij. De opleiding tot biersommelier aan het StiBON werd gestart en in maart 2017 afgerond. Samen met Tomas lanceerde ik een bierworkshop voor de horeca en slijterijen en heb ik inmiddels talloze proeverijen gegeven.”<br>
</div></div>
<p><img style="margin-bottom: -20.0px;" src="http://www.debierverteller.nl/wp-content/uploads/2015/12/bolhoed_zwart.png" alt="De Bierverteller Tomas Schroën Hubert Hecker" width="60" height="60"><br>
<span class="collapseomatic" id="id5dd511683b781" tabindex="" title="LUISA">LUISA</span></p><div id="target-id5dd511683b781" class="collapseomatic_content " style="display: none;">
<div style="max-width: 472px; margin-left: auto; margin-right: auto;"><img class="aligncenter size-full wp-image-989" src="http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-luisa.jpg" alt="Bierverteller Luisa Schroën Hlawatsch Utrecht" width="472" height="687" srcset="http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-luisa.jpg 472w, http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-luisa-206x300.jpg 206w" sizes="(max-width: 472px) 100vw, 472px"><br>
<strong><span style="color: #e63939;">a.k.a.:</span></strong> De Directeur<br>
<strong><span style="color: #e63939;">Geboortedatum:</span></strong> 23-08-1986<br>
<strong><span style="color: #e63939;">Geboren te:</span></strong> Halle (Westfalen)<br>
<strong><span style="color: #e63939;">Bierverteller sinds:</span></strong> Augustus 2017<br>
<strong><span style="color: #e63939;">Favoriete bierstijl:</span></strong> Berliner Weisse, Gose én alles met grote hoeveelheden hop<br>
<strong><span style="color: #e63939;">Specialiteit:</span></strong> Organiseren, plannen en overzicht houden<br>
<strong><span style="color: #e63939;">“Na de middelbare school verhuisde ik</span></strong> vanuit Duitsland naar Nederland, waar ik tijdens mijn studie Culturele Antropologie bij het Utrechtse Kafé België voor het eerst kennis heb mogen maken met de mooie wereld van speciaalbier –&nbsp; en ook met de charmante barman Tomas. 7 jaar later zijn wij getrouwd. Ik was volop bezig met mijn masterscriptie toen Tomas in 2016 de bierboetiek opende en vijf weken na de opening ziek werd. Na zijn overlijden besloot ik om de Bierverteller voort te zetten. Ik ben er langzaam ingerold, kreeg steeds meer inzicht in het bedrijf en begon een opleiding tot biersommelier bij StiBON. Sinds de zomer 2018 sta ik in de winkel, geïnspireerd door Tomas maar met een duidelijke eigen insteek. Ik ben gek op bier en het combineren van bier en spijs. Maar zeker niet alles draait om het product. De Bierverteller is een gemoedelijke huiskamer, een plek waar iets te beleven is en waar mensen bij elkaar komen. Zo organiseer ik als Bierverteller kleine optredens op het podium en geef ik lokale kunstenaars de ruimte om te exposeren.”<br>
</div></div>
<p><img style="margin-bottom: -20.0px;" src="http://www.debierverteller.nl/wp-content/uploads/2015/12/bolhoed_zwart.png" alt="De Bierverteller Tomas Schroën Hubert Hecker" width="60" height="60"><br>
<span class="collapseomatic " id="id5dd511683b7ca" tabindex="" title="SANNE">SANNE</span></p><div id="target-id5dd511683b7ca" class="collapseomatic_content " style="display: none;">
<div style="max-width: 472px; margin-left: auto; margin-right: auto;"><img class="aligncenter size-full wp-image-990" src="http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-sanne.jpg" alt="Bierverteller Sanne" width="472" height="687" srcset="http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-sanne.jpg 472w, http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-sanne-206x300.jpg 206w" sizes="(max-width: 472px) 100vw, 472px"><br>
<strong><span style="color: #e63939;">a.k.a.:</span></strong> “De Biercoach”<br>
<strong><span style="color: #e63939;">Geboortedatum:</span></strong> 21-11-1980<br>
<strong><span style="color: #e63939;">Geboren te:</span></strong> Oldenzaal<br>
<strong><span style="color: #e63939;">Bierverteller sinds:</span></strong> 1 januari 2019<br>
<strong><span style="color: #e63939;">Favoriete bierstijl:</span></strong> Zuur<br>
<strong><span style="color: #e63939;">Specialiteit:</span></strong> Bad en bier-pairings<br>
<strong><span style="color: #e63939;">“Geboren en getogen in Twente,</span></strong> waar ik in de thuiskroeg van mijn vader al op jonge leeftijd mocht helpen met tappen en serveren. Op gepaste leeftijd kwam het proeven erbij en was mijn passie voor bier geboren. Een aantal jaar geleden ben ik verhuisd naar Utrecht, gestart met de opleiding tot biersommelier, gaan werken voor een Utrechtse brouwerij en mag ik mijzelf sinds januari 2019 Bierverteller noemen. Omdat bier een prachtig en gevarieerd product is, ben ik ervan overtuigd dat er voor iedereen, op ieder moment, in iedere situatie een geschikt biertje bestaat. Een bier voor bij het badderen, tijdens het bouwen van een legendarische legoset of als kadootje voor jezelf – ik help je graag in je zoektocht!”<br>
</div></div>
<p><img style="margin-bottom: -20.0px;" src="http://www.debierverteller.nl/wp-content/uploads/2015/12/bolhoed_zwart.png" alt="De Bierverteller Tomas Schroën Hubert Hecker" width="60" height="60"><br>
<span class="collapseomatic  colomat-visited" id="id5dd511683b815" tabindex="" title="TOMAS †">TOMAS †</span></p><div id="target-id5dd511683b815" class="collapseomatic_content " style="display: none;">
<div style="max-width: 472px; margin-left: auto; margin-right: auto;"><img class="aligncenter size-full wp-image-1018" src="http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-tomas-2.jpg" alt="Bierverteller Tomas Schroën" width="472" height="687" srcset="http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-tomas-2.jpg 472w, http://www.debierverteller.nl/wp-content/uploads/2019/04/bierverteller-tomas-2-206x300.jpg 206w" sizes="(max-width: 472px) 100vw, 472px"><br>
<strong><span style="color: #e63939;">a.k.a.:</span></strong> “The Founding Father”<br>
<strong><span style="color: #e63939;">Geboortedatum:</span></strong> 12-10-1983 <strong><span style="color: #e63939;">†:</span></strong> 02-08-2017<br>
<strong><span style="color: #e63939;">Geboren te:</span></strong> Weert<br>
<strong><span style="color: #e63939;">Bierverteller sinds:</span></strong> April 2012<br>
<strong><span style="color: #e63939;">Favoriete bierstijl:</span></strong> Gerookt<br>
<strong><span style="color: #e63939;">Specialiteit:</span></strong> Culicombi’s &amp; Entertainment<br>
<strong><span style="color: #e63939;">Medio mei 2017 schreef Tomas:</span></strong> “Na twee jaar toneelschool, een Bachelor geschiedenis aan de UU en jaren ervaring achter de bar van Kafé België besloot ik in 2012 een eigen bedrijf te beginnen. Mijn passie voor het vertellen van verhalen, presenteren, geschiedenis en bier leidde tot het ontstaan van De Bierverteller. Wat begon met één bierproeverij per maand, werden al snel verschillende proeverijen per week door het hele land. Na een paar jaar kon ik mij volledig richten op mijn bedrijf en stoppen met werken achter de bar. Een opleiding tot biersommelier bij StiBON bracht mij meer inhoudelijke kennis en de activiteiten van De Bierverteller breidden zich uit. In augustus 2016 opende De Bierverteller Bierboetiek haar deuren. Een nieuw hoofdstuk van een spannend avontuur.”</div></div>
</div>
<img class="alignnone size-full wp-image-108"  src="http://www.debierverteller.nl/wp-content/uploads/2015/01/1_de_bierverteller_proeverijen_900x560.png" style="background-image: url('http://www.debierverteller.nl/test/wp-content/uploads/2015/01/tile_bg_rood_44x80.png');" alt="de bierverteller proeverijen Utrecht" width="900" height="560" srcset="http://www.debierverteller.nl/wp-content/uploads/2015/01/1_de_bierverteller_proeverijen_900x560.png 900w, http://www.debierverteller.nl/wp-content/uploads/2015/01/1_de_bierverteller_proeverijen_900x560-300x187.png 300w, http://www.debierverteller.nl/wp-content/uploads/2015/01/1_de_bierverteller_proeverijen_900x560-624x388.png 624w" sizes="(max-width: 900px) 100vw, 900px">
</section>
